version: 0.0
os: linux
files:
  - source: dist/
    destination: /var/www/html/
    overwrite: true
  - source: scripts/
    destination: /var/www/html/scripts/
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh 
      timeout: 300
      runas: root
  # AGREGA ESTE HOOK
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
