version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    # Estas tres líneas deben ir dentro del mismo bloque '-'
    overwrite: true
    file_exists_behavior: OVERWRITE 

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
