version: 0.2
phases:
  install:
    commands:
      - echo Instalando dependencias...
      - npm install
  build:
    commands:
      - echo Compilando el proyecto...
      - npm run build
      
artifacts:
  files:
    # 1. Incluir el archivo appspec.yml de la raíz del repositorio
    - appspec.yml
    # 2. Incluir la carpeta scripts
    - scripts/**/*
    # 3. Incluir el contenido de la carpeta dist (compilado)
    - dist/**/* # CAMBIO CLAVE: Cambiar el base-directory a la raíz del proyecto para que pueda incluir todos los archivos.
  base-directory: .
