version: 0.2
phases:
  install:
    commands:
      - echo Instalando dependencias...
      - npm install
  build:
    commands:
      - echo Compilando el proyecto...
      - npm run build
      # AGREGA ESTA LÍNEA: Mueve el .htaccess a dist para que se despliegue junto con el build
      - cp .htaccess dist/ 

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - dist/**/*
    # Ya no necesitas listar .htaccess aquí por separado si está dentro de dist
  base-directory: .
